import { pgTable, uuid, varchar, text, timestamp, boolean, jsonb, integer, unique } from 'drizzle-orm/pg-core'
import { relations, sql } from 'drizzle-orm'

// ============================================
// IMPORTANT: ID Generation Rule
// All IDs must be generated by the application, NOT by the database.
// Use crypto.randomUUID() or similar in your application code.
// This enables better data migration and sync capabilities.
// ============================================

// ============================================
// USERS & AUTHENTICATION
// ============================================

export const users = pgTable('users', {
  id: uuid('id').primaryKey(), // Application-generated UUID
  email: varchar('email', { length: 255 }).notNull().unique(),
  name: varchar('name', { length: 255 }).notNull(),
  avatarUrl: text('avatar_url'),
  preferences: jsonb('preferences').default({}).notNull(),
  createdAt: timestamp('created_at', { withTimezone: true }).defaultNow().notNull(),
  updatedAt: timestamp('updated_at', { withTimezone: true }).defaultNow().notNull(),
  lastLoginAt: timestamp('last_login_at', { withTimezone: true }),
  isActive: boolean('is_active').default(true).notNull(),
})

export const userAccounts = pgTable('user_accounts', {
  id: uuid('id').primaryKey(), // Application-generated UUID
  userId: uuid('user_id').notNull().references(() => users.id, { onDelete: 'cascade' }),
  provider: varchar('provider', { length: 50 }).notNull(), // 'password', 'google', 'github', 'microsoft', 'saml'
  providerAccountId: varchar('provider_account_id', { length: 255 }).notNull(),
  passwordHash: varchar('password_hash', { length: 255 }),
  lastPasswordUpdate: timestamp('last_password_update', { withTimezone: true }),
  accessToken: text('access_token'),
  refreshToken: text('refresh_token'),
  expiresAt: timestamp('expires_at', { withTimezone: true }),
  metadata: jsonb('metadata').default({}).notNull(),
  createdAt: timestamp('created_at', { withTimezone: true }).defaultNow().notNull(),
  updatedAt: timestamp('updated_at', { withTimezone: true }).defaultNow().notNull(),
}, (table) => [
  unique('unique_provider_account').on(table.provider, table.providerAccountId),
])

// ============================================
// COMPANY & MEMBERS
// ============================================

export const companies = pgTable('companies', {
  id: uuid('id').primaryKey(), // Application-generated UUID
  name: varchar('name', { length: 255 }).notNull(),
  slug: varchar('slug', { length: 255 }).notNull().unique(),
  ownerId: uuid('owner_id').notNull().references(() => users.id),
  settings: jsonb('settings').default({
    timezone: 'UTC',
    dateFormat: 'YYYY-MM-DD',
    defaultLanguage: 'en',
    theme: {},
  }).notNull(),
  createdAt: timestamp('created_at', { withTimezone: true }).defaultNow().notNull(),
  updatedAt: timestamp('updated_at', { withTimezone: true }).defaultNow().notNull(),
  deletedAt: timestamp('deleted_at', { withTimezone: true }),
})

export const companyMembers = pgTable('company_members', {
  id: uuid('id').primaryKey(), // Application-generated UUID
  companyId: uuid('company_id').notNull().references(() => companies.id, { onDelete: 'cascade' }),
  userId: uuid('user_id').notNull().references(() => users.id, { onDelete: 'cascade' }),
  role: varchar('role', { length: 20 }).notNull().$type<'admin' | 'member'>(),
  joinedAt: timestamp('joined_at', { withTimezone: true }).defaultNow().notNull(),
  invitedBy: uuid('invited_by').references(() => users.id),
}, (table) => [
  unique('unique_company_member').on(table.companyId, table.userId),
])

export const userGroups = pgTable('user_groups', {
  id: uuid('id').primaryKey(), // Application-generated UUID
  companyId: uuid('company_id').notNull().references(() => companies.id, { onDelete: 'cascade' }),
  name: varchar('name', { length: 255 }).notNull(),
  description: text('description'),
  createdBy: uuid('created_by').notNull().references(() => users.id),
  createdAt: timestamp('created_at', { withTimezone: true }).defaultNow().notNull(),
  updatedAt: timestamp('updated_at', { withTimezone: true }).defaultNow().notNull(),
})

export const userGroupMembers = pgTable('user_group_members', {
  id: uuid('id').primaryKey(), // Application-generated UUID
  companyId: uuid('company_id').notNull().references(() => companies.id, { onDelete: 'cascade' }), // Added for easy query & sync
  groupId: uuid('group_id').notNull().references(() => userGroups.id, { onDelete: 'cascade' }),
  userId: uuid('user_id').notNull().references(() => users.id, { onDelete: 'cascade' }),
  role: varchar('role', { length: 20 }).notNull().$type<'admin' | 'member'>(),
  addedBy: uuid('added_by').notNull().references(() => users.id),
  addedAt: timestamp('added_at', { withTimezone: true }).defaultNow().notNull(),
}, (table) => [
  unique('unique_group_member').on(table.groupId, table.userId),
])

export const inviteLinks = pgTable('invite_links', {
  id: uuid('id').primaryKey(), // Application-generated UUID
  companyId: uuid('company_id').notNull().references(() => companies.id, { onDelete: 'cascade' }),
  createdBy: uuid('created_by').notNull().references(() => users.id),
  token: varchar('token', { length: 255 }).notNull().unique(),
  role: varchar('role', { length: 20 }).notNull().$type<'admin' | 'member'>(),
  maxUses: integer('max_uses'),
  usedCount: integer('used_count').default(0).notNull(),
  expiresAt: timestamp('expires_at', { withTimezone: true }),
  createdAt: timestamp('created_at', { withTimezone: true }).defaultNow().notNull(),
  usedAt: timestamp('used_at', { withTimezone: true }),
  usedBy: uuid('used_by').references(() => users.id),
  isActive: boolean('is_active').default(true).notNull(),
})

// ============================================
// WORKSPACE & FOLDERS
// ============================================

// Menu item type for JSONB
interface MenuItem {
  id: string
  type: 'folder' | 'table' | 'view' | 'dashboard'
  itemId: string
  order: number
  children?: MenuItem[]
  permissions: {
    read: string[]
    readwrite: string[]
    manage: string[]
  }
}

export const workspaces = pgTable('workspaces', {
  id: uuid('id').primaryKey(), // Application-generated UUID
  companyId: uuid('company_id').notNull().references(() => companies.id, { onDelete: 'cascade' }),
  name: varchar('name', { length: 255 }).notNull(),
  description: text('description'),
  icon: varchar('icon', { length: 50 }),
  color: varchar('color', { length: 7 }),
  menu: jsonb('menu').$type<MenuItem[]>().default([]).notNull(),
  createdBy: uuid('created_by').notNull().references(() => users.id),
  createdAt: timestamp('created_at', { withTimezone: true }).defaultNow().notNull(),
  updatedAt: timestamp('updated_at', { withTimezone: true }).defaultNow().notNull(),
  deletedAt: timestamp('deleted_at', { withTimezone: true }),
})

// Folders are flat - hierarchy is in workspace.menu JSONB
export const folders = pgTable('folders', {
  id: uuid('id').primaryKey(), // Application-generated UUID
  companyId: uuid('company_id').notNull().references(() => companies.id, { onDelete: 'cascade' }),
  workspaceId: uuid('workspace_id').notNull().references(() => workspaces.id, { onDelete: 'cascade' }),
  // Note: parent_id removed - hierarchy is in workspace.menu JSONB
  name: varchar('name', { length: 255 }).notNull(),
  icon: varchar('icon', { length: 50 }),
  color: varchar('color', { length: 7 }),
  orderIndex: integer('order_index').default(0).notNull(),
  createdBy: uuid('created_by').notNull().references(() => users.id),
  createdAt: timestamp('created_at', { withTimezone: true }).defaultNow().notNull(),
  updatedAt: timestamp('updated_at', { withTimezone: true }).defaultNow().notNull(),
  deletedAt: timestamp('deleted_at', { withTimezone: true }),
})

// ============================================
// RELATIONS (for Drizzle ORM query builder)
// ============================================

export const usersRelations = relations(users, ({ many }) => ({
  accounts: many(userAccounts),
  ownedCompanies: many(companies, { relationName: 'owner' }),
  memberships: many(companyMembers),
  groupMemberships: many(userGroupMembers),
}))

export const userAccountsRelations = relations(userAccounts, ({ one }) => ({
  user: one(users, {
    fields: [userAccounts.userId],
    references: [users.id],
  }),
}))

export const companiesRelations = relations(companies, ({ one, many }) => ({
  owner: one(users, {
    fields: [companies.ownerId],
    references: [users.id],
  }),
  members: many(companyMembers),
  groups: many(userGroups),
  workspaces: many(workspaces),
  folders: many(folders),
  inviteLinks: many(inviteLinks),
}))

export const companyMembersRelations = relations(companyMembers, ({ one }) => ({
  company: one(companies, {
    fields: [companyMembers.companyId],
    references: [companies.id],
  }),
  user: one(users, {
    fields: [companyMembers.userId],
    references: [users.id],
  }),
  invitedByUser: one(users, {
    fields: [companyMembers.invitedBy],
    references: [users.id],
  }),
}))

export const userGroupsRelations = relations(userGroups, ({ one, many }) => ({
  company: one(companies, {
    fields: [userGroups.companyId],
    references: [companies.id],
  }),
  members: many(userGroupMembers),
  createdByUser: one(users, {
    fields: [userGroups.createdBy],
    references: [users.id],
  }),
}))

export const userGroupMembersRelations = relations(userGroupMembers, ({ one }) => ({
  company: one(companies, {
    fields: [userGroupMembers.companyId],
    references: [companies.id],
  }),
  group: one(userGroups, {
    fields: [userGroupMembers.groupId],
    references: [userGroups.id],
  }),
  user: one(users, {
    fields: [userGroupMembers.userId],
    references: [users.id],
  }),
  addedByUser: one(users, {
    fields: [userGroupMembers.addedBy],
    references: [users.id],
  }),
}))

export const inviteLinksRelations = relations(inviteLinks, ({ one }) => ({
  company: one(companies, {
    fields: [inviteLinks.companyId],
    references: [companies.id],
  }),
  createdByUser: one(users, {
    fields: [inviteLinks.createdBy],
    references: [users.id],
  }),
  usedByUser: one(users, {
    fields: [inviteLinks.usedBy],
    references: [users.id],
  }),
}))

export const workspacesRelations = relations(workspaces, ({ one, many }) => ({
  company: one(companies, {
    fields: [workspaces.companyId],
    references: [companies.id],
  }),
  createdByUser: one(users, {
    fields: [workspaces.createdBy],
    references: [users.id],
  }),
  folders: many(folders),
}))

export const foldersRelations = relations(folders, ({ one }) => ({
  company: one(companies, {
    fields: [folders.companyId],
    references: [companies.id],
  }),
  workspace: one(workspaces, {
    fields: [folders.workspaceId],
    references: [workspaces.id],
  }),
  createdByUser: one(users, {
    fields: [folders.createdBy],
    references: [users.id],
  }),
}))
