import {
  pgTable,
  uuid,
  varchar,
  text,
  timestamp,
  boolean,
  jsonb,
  integer,
  unique,
} from "drizzle-orm/pg-core";
import { relations, sql } from "drizzle-orm";

// ============================================
// IMPORTANT: ID Generation Rule
// All IDs must be generated by the application, NOT by the database.
// Use crypto.randomUUID() or similar in your application code.
// This enables better data migration and sync capabilities.
// ============================================

// ============================================
// USERS & AUTHENTICATION
// ============================================

export const users = pgTable("users", {
  id: uuid("id").primaryKey(), // Application-generated UUID
  email: varchar("email", { length: 255 }).notNull().unique(),
  name: varchar("name", { length: 255 }).notNull(),
  avatarUrl: text("avatar_url"),
  preferences: jsonb("preferences").default({}).notNull(),
  createdAt: timestamp("created_at", { withTimezone: true })
    .defaultNow()
    .notNull(),
  updatedAt: timestamp("updated_at", { withTimezone: true })
    .defaultNow()
    .notNull(),
  lastLoginAt: timestamp("last_login_at", { withTimezone: true }),
  isActive: boolean("is_active").default(true).notNull(),
});

export const userAccounts = pgTable(
  "user_accounts",
  {
    id: uuid("id").primaryKey(), // Application-generated UUID
    userId: uuid("user_id").notNull(), // No FK - references users.id
    provider: varchar("provider", { length: 50 }).notNull(), // 'password', 'google', 'github', 'microsoft', 'saml'
    providerAccountId: varchar("provider_account_id", {
      length: 255,
    }).notNull(),
    passwordHash: varchar("password_hash", { length: 255 }),
    lastPasswordUpdate: timestamp("last_password_update", {
      withTimezone: true,
    }),
    accessToken: text("access_token"),
    refreshToken: text("refresh_token"),
    expiresAt: timestamp("expires_at", { withTimezone: true }),
    metadata: jsonb("metadata").default({}).notNull(),
    createdAt: timestamp("created_at", { withTimezone: true })
      .defaultNow()
      .notNull(),
    updatedAt: timestamp("updated_at", { withTimezone: true })
      .defaultNow()
      .notNull(),
  },
  (table) => [
    unique("unique_provider_account").on(
      table.provider,
      table.providerAccountId,
    ),
  ],
);

// ============================================
// COMPANY & MEMBERS
// ============================================

export const companies = pgTable("companies", {
  id: uuid("id").primaryKey(), // Application-generated UUID
  name: varchar("name", { length: 255 }).notNull(),
  slug: varchar("slug", { length: 255 }).notNull().unique(),
  ownerId: uuid("owner_id").notNull(), // No FK - references users.id
  plan: varchar("plan", { length: 24 })
    .notNull()
    .$type<"basic" | "pro" | "enterprise">()
    .default("basic"),
  settings: jsonb("settings")
    .default({
      timezone: "UTC",
      dateFormat: "YYYY-MM-DD",
      defaultLanguage: "en",
      theme: {},
    })
    .notNull(),
  createdAt: timestamp("created_at", { withTimezone: true })
    .defaultNow()
    .notNull(),
  updatedAt: timestamp("updated_at", { withTimezone: true })
    .defaultNow()
    .notNull(),
  deletedAt: timestamp("deleted_at", { withTimezone: true }),
});

export const companyMembers = pgTable(
  "company_members",
  {
    id: uuid("id").primaryKey(), // Application-generated UUID
    companyId: uuid("company_id").notNull(), // No FK - references companies.id
    userId: uuid("user_id").notNull(), // No FK - references users.id
    role: varchar("role", { length: 20 }).notNull().$type<"admin" | "member">(),
    joinedAt: timestamp("joined_at", { withTimezone: true })
      .defaultNow()
      .notNull(),
    invitedBy: uuid("invited_by"), // No FK - references users.id
  },
  (table) => [
    unique("unique_company_member").on(table.companyId, table.userId),
  ],
);

export const userGroups = pgTable("user_groups", {
  id: uuid("id").primaryKey(), // Application-generated UUID
  companyId: uuid("company_id").notNull(), // No FK - references companies.id
  name: varchar("name", { length: 255 }).notNull(),
  description: text("description"),
  createdBy: uuid("created_by").notNull(), // No FK - references users.id
  createdAt: timestamp("created_at", { withTimezone: true })
    .defaultNow()
    .notNull(),
  updatedAt: timestamp("updated_at", { withTimezone: true })
    .defaultNow()
    .notNull(),
});

export const userGroupMembers = pgTable(
  "user_group_members",
  {
    id: uuid("id").primaryKey(), // Application-generated UUID
    companyId: uuid("company_id").notNull(), // No FK - references companies.id
    groupId: uuid("group_id").notNull(), // No FK - references user_groups.id
    userId: uuid("user_id").notNull(), // No FK - references users.id
    role: varchar("role", { length: 20 }).notNull().$type<"admin" | "member">(),
    addedBy: uuid("added_by").notNull(), // No FK - references users.id
    addedAt: timestamp("added_at", { withTimezone: true })
      .defaultNow()
      .notNull(),
  },
  (table) => [unique("unique_group_member").on(table.groupId, table.userId)],
);

export const inviteLinks = pgTable("invite_links", {
  id: uuid("id").primaryKey(), // Application-generated UUID
  companyId: uuid("company_id").notNull(), // No FK - references companies.id
  createdBy: uuid("created_by").notNull(), // No FK - references users.id
  email: varchar("email", { length: 255 }), // NEW: One invite per email per company
  token: varchar("token", { length: 255 }).notNull().unique(),
  role: varchar("role", { length: 20 }).notNull().$type<"admin" | "member">(),
  // REMOVED: maxUses, usedCount - one invite per person model
  expiresAt: timestamp("expires_at", { withTimezone: true }),
  createdAt: timestamp("created_at", { withTimezone: true })
    .defaultNow()
    .notNull(),
  usedAt: timestamp("used_at", { withTimezone: true }),
  usedBy: uuid("used_by"), // No FK - references users.id
  isActive: boolean("is_active").default(true).notNull(),
});

// ============================================
// SPACE & ITEMS (Unified Design)
// ============================================

export const spaces = pgTable("spaces", {
  id: uuid("id").primaryKey(),
  companyId: uuid("company_id").notNull(), // No FK - references companies.id
  name: varchar("name", { length: 255 }).notNull(),
  description: text("description"),
  icon: varchar("icon", { length: 50 }),
  color: varchar("color", { length: 7 }),
  settings: jsonb("settings").default({}).notNull(),
  createdBy: uuid("created_by").notNull(), // No FK - references users.id
  createdAt: timestamp("created_at", { withTimezone: true })
    .defaultNow()
    .notNull(),
  updatedAt: timestamp("updated_at", { withTimezone: true })
    .defaultNow()
    .notNull(),
  deletedAt: timestamp("deleted_at", { withTimezone: true }),
});

export const spaceMembers = pgTable(
  "space_members",
  {
    id: uuid("id").primaryKey(),
    spaceId: uuid("space_id").notNull(), // No FK - references spaces.id
    userId: uuid("user_id").notNull(), // No FK - references users.id
    role: varchar("role", { length: 20 })
      .notNull()
      .$type<"admin" | "editor" | "viewer">(),
    joinedAt: timestamp("joined_at", { withTimezone: true })
      .defaultNow()
      .notNull(),
    invitedBy: uuid("invited_by"), // No FK - references users.id
  },
  (table) => [unique("unique_space_member").on(table.spaceId, table.userId)],
);

// Unified items table - folder, table, view, dashboard all in one
export const spaceItems = pgTable("space_items", {
  id: uuid("id").primaryKey(),
  spaceId: uuid("space_id").notNull(), // No FK - references spaces.id
  parentId: uuid("parent_id"), // No FK - references space_items.id (self-reference)
  type: varchar("type", { length: 50 })
    .notNull()
    .$type<"folder" | "table" | "view" | "dashboard">(),
  name: varchar("name", { length: 255 }).notNull(),
  description: text("description"),
  icon: varchar("icon", { length: 50 }),
  color: varchar("color", { length: 7 }),
  orderIndex: integer("order_index").default(0).notNull(),
  config: jsonb("config").default({}).notNull(),
  createdBy: uuid("created_by").notNull(), // No FK - references users.id
  createdAt: timestamp("created_at", { withTimezone: true })
    .defaultNow()
    .notNull(),
  updatedAt: timestamp("updated_at", { withTimezone: true })
    .defaultNow()
    .notNull(),
  deletedAt: timestamp("deleted_at", { withTimezone: true }),
});

// Item-level permissions - extends space membership
export const spaceItemPermissions = pgTable(
  "space_item_permissions",
  {
    id: uuid("id").primaryKey(),
    itemId: uuid("item_id").notNull(), // No FK - references space_items.id
    userId: uuid("user_id").notNull(), // No FK - references users.id
    permission: varchar("permission", { length: 20 })
      .notNull()
      .$type<"read" | "readwrite" | "manage">(),
    createdAt: timestamp("created_at", { withTimezone: true })
      .defaultNow()
      .notNull(),
  },
  (table) => [
    unique("unique_item_user_permission").on(table.itemId, table.userId),
  ],
);

// ============================================
// RELATIONS (for Drizzle ORM query builder)
// ============================================

export const usersRelations = relations(users, ({ many }) => ({
  accounts: many(userAccounts),
  ownedCompanies: many(companies, { relationName: "owner" }),
  memberships: many(companyMembers),
  groupMemberships: many(userGroupMembers),
}));

export const userAccountsRelations = relations(userAccounts, ({ one }) => ({
  user: one(users, {
    fields: [userAccounts.userId],
    references: [users.id],
  }),
}));

export const companiesRelations = relations(companies, ({ one, many }) => ({
  owner: one(users, {
    fields: [companies.ownerId],
    references: [users.id],
  }),
  members: many(companyMembers),
  groups: many(userGroups),
  spaces: many(spaces),
  inviteLinks: many(inviteLinks),
}));

export const companyMembersRelations = relations(companyMembers, ({ one }) => ({
  company: one(companies, {
    fields: [companyMembers.companyId],
    references: [companies.id],
  }),
  user: one(users, {
    fields: [companyMembers.userId],
    references: [users.id],
  }),
  invitedByUser: one(users, {
    fields: [companyMembers.invitedBy],
    references: [users.id],
  }),
}));

export const userGroupsRelations = relations(userGroups, ({ one, many }) => ({
  company: one(companies, {
    fields: [userGroups.companyId],
    references: [companies.id],
  }),
  members: many(userGroupMembers),
  createdByUser: one(users, {
    fields: [userGroups.createdBy],
    references: [users.id],
  }),
}));

export const userGroupMembersRelations = relations(
  userGroupMembers,
  ({ one }) => ({
    company: one(companies, {
      fields: [userGroupMembers.companyId],
      references: [companies.id],
    }),
    group: one(userGroups, {
      fields: [userGroupMembers.groupId],
      references: [userGroups.id],
    }),
    user: one(users, {
      fields: [userGroupMembers.userId],
      references: [users.id],
    }),
    addedByUser: one(users, {
      fields: [userGroupMembers.addedBy],
      references: [users.id],
    }),
  }),
);

export const inviteLinksRelations = relations(inviteLinks, ({ one }) => ({
  company: one(companies, {
    fields: [inviteLinks.companyId],
    references: [companies.id],
  }),
  createdByUser: one(users, {
    fields: [inviteLinks.createdBy],
    references: [users.id],
  }),
  usedByUser: one(users, {
    fields: [inviteLinks.usedBy],
    references: [users.id],
  }),
}));

// Space Relations
export const spacesRelations = relations(spaces, ({ one, many }) => ({
  company: one(companies, {
    fields: [spaces.companyId],
    references: [companies.id],
  }),
  createdByUser: one(users, {
    fields: [spaces.createdBy],
    references: [users.id],
  }),
  members: many(spaceMembers),
  items: many(spaceItems),
}));

export const spaceMembersRelations = relations(spaceMembers, ({ one }) => ({
  space: one(spaces, {
    fields: [spaceMembers.spaceId],
    references: [spaces.id],
  }),
  user: one(users, {
    fields: [spaceMembers.userId],
    references: [users.id],
  }),
  invitedByUser: one(users, {
    fields: [spaceMembers.invitedBy],
    references: [users.id],
  }),
}));

export const spaceItemsRelations = relations(spaceItems, ({ one, many }) => ({
  space: one(spaces, {
    fields: [spaceItems.spaceId],
    references: [spaces.id],
  }),
  parent: one(spaceItems, {
    fields: [spaceItems.parentId],
    references: [spaceItems.id],
  }),
  createdByUser: one(users, {
    fields: [spaceItems.createdBy],
    references: [users.id],
  }),
  permissions: many(spaceItemPermissions),
}));

export const spaceItemPermissionsRelations = relations(
  spaceItemPermissions,
  ({ one }) => ({
    item: one(spaceItems, {
      fields: [spaceItemPermissions.itemId],
      references: [spaceItems.id],
    }),
    user: one(users, {
      fields: [spaceItemPermissions.userId],
      references: [users.id],
    }),
  }),
);

// ============================================
// SPACE ITEM COLUMNS & ROWS (FEAT-021)
// ============================================

export const spaceItemColumns = pgTable(
  "space_item_columns",
  {
    id: uuid("id").primaryKey(),
    itemId: uuid("item_id").notNull(), // 指向 space_items (一定是 Table)
    
    name: varchar("name", { length: 255 }).notNull(),
    key: varchar("key", { length: 255 }).notNull(), // 唯一 key (自動生成)
    
    // Column 分類: information, relation, dynamic
    category: varchar("category", { length: 20 }).notNull(),
    
    // 具體類型
    type: varchar("type", { length: 50 }).notNull(),
    
    orderIndex: integer("order_index").default(0).notNull(),
    
    // 配置 (根據 type 不同結構)
    config: jsonb("config").default({}).notNull(),
    
    // 預設值
    defaultValue: jsonb("default_value"),
    
    createdAt: timestamp("created_at", { withTimezone: true })
      .defaultNow()
      .notNull(),
    updatedAt: timestamp("updated_at", { withTimezone: true })
      .defaultNow()
      .notNull(),
    deletedAt: timestamp("deleted_at", { withTimezone: true }),
  },
  (table) => [
    unique("unique_item_column_key").on(table.itemId, table.key),
  ],
);

export const spaceItemRows = pgTable("space_item_rows", {
  id: uuid("id").primaryKey(),
  companyId: uuid("company_id").notNull(), // Partition key
  spaceId: uuid("space_id").notNull(),
  itemId: uuid("item_id").notNull(), // 指向 Table (不是 View)
  
  // 數據存 JSONB
  data: jsonb("data").default({}).notNull(),
  
  // Metadata
  createdBy: uuid("created_by").notNull(),
  createdAt: timestamp("created_at", { withTimezone: true })
    .defaultNow()
    .notNull(),
  updatedBy: uuid("updated_by"),
  updatedAt: timestamp("updated_at", { withTimezone: true }),
  deletedBy: uuid("deleted_by"),
  deletedAt: timestamp("deleted_at", { withTimezone: true }),
});

// ============================================
// RELATIONS for new tables
// ============================================

export const spaceItemColumnsRelations = relations(spaceItemColumns, ({ one }) => ({
  item: one(spaceItems, {
    fields: [spaceItemColumns.itemId],
    references: [spaceItems.id],
  }),
}));

export const spaceItemRowsRelations = relations(spaceItemRows, ({ one }) => ({
  item: one(spaceItems, {
    fields: [spaceItemRows.itemId],
    references: [spaceItems.id],
  }),
}));
